version: "3.8"
services:
  jenkins:
    image: jenkins/jenkins
    restart: always
    ports:
      - "8080:8080"
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/mysql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: tingeso2
    ports:
      - "5432:5432"
  app:
    container_name: evaluacion1tingeso
    image: eduardops1907/evaluacion1tingeso
    ports:
      - "8090:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/tingeso2?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres